
import React, { useContext, useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { AppContext } from '../context/AppContext';
import { Role, Quiz, Question, User, Class, Category } from '../types';
import {
  PlusCircleIcon,
  PencilIcon,
  TrashIcon,
  DocumentDuplicateIcon,
  ChartBarIcon,
  TagIcon,
  ClockIcon,
  DocumentTextIcon,
  PrinterIcon,
  IdCardIcon,
} from '../components/icons';

// Common styles
const tabStyle = "flex items-center px-3 py-2 font-medium text-sm rounded-md whitespace-nowrap";
const activeTabStyle = "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/50 dark:text-indigo-300";
const inactiveTabStyle = "text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200";
const buttonStyle = "flex items-center space-x-2 px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 disabled:bg-indigo-300 disabled:cursor-not-allowed transition-colors";
const secondaryButtonStyle = "flex items-center space-x-2 px-4 py-2 bg-gray-200 dark:bg-gray-600 text-gray-800 dark:text-gray-100 rounded-md hover:bg-gray-300 dark:hover:bg-gray-500 transition-colors";
const actionIconStyle = "text-gray-500 hover:text-indigo-600 dark:hover:text-indigo-400 p-1 rounded-md disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:text-gray-500";
const deleteIconStyle = "text-gray-500 hover:text-red-600 dark:hover:text-red-400 p-1 rounded-md disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:text-gray-500";
const deleteButtonStyle = "flex items-center space-x-2 px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 disabled:bg-red-300 disabled:cursor-not-allowed transition-colors";
const inputStyle = "w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-gray-200 focus:outline-none focus:ring-2 focus:ring-indigo-500";


// #region Modals and Forms

const Modal: React.FC<{ children: React.ReactNode; title: string; onClose: () => void; size?: 'md' | 'lg' | 'xl' | '2xl' | '3xl' }> = ({ children, title, onClose, size = '2xl' }) => {
    return (
        <div className="fixed inset-0 bg-black bg-opacity-60 z-50 flex justify-center items-start pt-10 print:static print:bg-transparent print:p-0" onClick={onClose}>
            <div className={`bg-white dark:bg-gray-800 rounded-lg shadow-xl w-full max-w-${size} max-h-[90vh] flex flex-col print:shadow-none print:max-h-none print:w-full print:max-w-none`} onClick={e => e.stopPropagation()}>
                <div className="flex justify-between items-center p-4 border-b dark:border-gray-700 sticky top-0 bg-white dark:bg-gray-800 rounded-t-lg no-print">
                    <h3 className="text-xl font-semibold text-gray-900 dark:text-white">{title}</h3>
                    <button onClick={onClose} className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 p-1 rounded-full">
                         <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" /></svg>
                    </button>
                </div>
                <div className="overflow-y-auto print:overflow-visible">
                    {children}
                </div>
            </div>
        </div>
    );
};

const ConfirmationModal: React.FC<{
    title: string;
    message: string;
    onConfirm: () => void;
    onCancel: () => void;
}> = ({ title, message, onConfirm, onCancel }) => {
    return (
        <Modal title={title} onClose={onCancel} size="md">
            <div className="p-6">
                <p className="text-gray-600 dark:text-gray-300">{message}</p>
            </div>
            <div className="flex justify-end space-x-3 p-4 bg-gray-50 dark:bg-gray-900/50 rounded-b-lg">
                <button type="button" onClick={onCancel} className={secondaryButtonStyle}>Cancel</button>
                <button type="button" onClick={onConfirm} className={deleteButtonStyle}>Confirm Delete</button>
            </div>
        </Modal>
    );
};

const UserModal: React.FC<{ user?: User; onSave: (user: User) => void; onCancel: () => void }> = ({ user, onSave, onCancel }) => {
    const [name, setName] = useState(user?.name || '');
    const [role, setRole] = useState(user?.role || Role.USER);

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        onSave({
            id: user?.id || `user-${Date.now()}`,
            name,
            role,
            uniqueId: user?.uniqueId || '' // Will be generated by context if new
        });
    };

    return (
        <Modal title={user ? 'Edit User' : 'Create User'} onClose={onCancel}>
            <form onSubmit={handleSubmit} className="space-y-4 p-6">
                {user && (
                    <div>
                        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Unique ID</label>
                        <p className="px-3 py-2 bg-gray-100 dark:bg-gray-700 rounded-md text-gray-500 dark:text-gray-400">{user.uniqueId}</p>
                    </div>
                )}
                <div>
                    <label className="block text-sm font-medium mb-1">Name</label>
                    <input type="text" value={name} onChange={e => setName(e.target.value)} className={inputStyle} required />
                </div>
                <div>
                    <label className="block text-sm font-medium mb-1">Role</label>
                    <select value={role} onChange={e => setRole(e.target.value as Role)} className={inputStyle}>
                        <option value={Role.USER}>User</option>
                        <option value={Role.ADMIN}>Admin</option>
                    </select>
                </div>
                <div className="flex justify-end space-x-3 pt-4">
                    <button type="button" onClick={onCancel} className={secondaryButtonStyle}>Cancel</button>
                    <button type="submit" className={buttonStyle}>Save User</button>
                </div>
            </form>
        </Modal>
    );
};

const IdCardModal: React.FC<{ user: User; onClose: () => void }> = ({ user, onClose }) => {
    return (
        <Modal title="User ID Card" onClose={onClose} size="md">
            <div className="p-6">
                <div className="printable-content bg-white dark:bg-gray-800 rounded-lg border-2 border-dashed dark:border-gray-600 p-6 flex flex-col items-center text-center w-[350px] mx-auto">
                    <div className="flex items-center space-x-2 w-full mb-4">
                        <div className="bg-indigo-600 p-2 rounded-lg">
                            <svg className="w-5 h-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                            </svg>
                        </div>
                        <h2 className="text-xl font-bold text-gray-800 dark:text-white">MSQ Pro</h2>
                    </div>

                    <div className="w-24 h-24 rounded-full bg-gray-200 dark:bg-gray-700 flex items-center justify-center mb-4">
                        <svg className="w-16 h-16 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
                        </svg>
                    </div>

                    <h3 className="text-2xl font-bold text-gray-900 dark:text-white">{user.name}</h3>
                    <p className={`text-sm font-medium mb-6 ${user.role === Role.ADMIN ? 'text-indigo-500' : 'text-green-500'}`}>{user.role}</p>

                    <div className="bg-gray-100 dark:bg-gray-700/50 rounded-lg p-4 w-full">
                        <h4 className="font-semibold text-gray-600 dark:text-gray-300 mb-2">Login Credentials</h4>
                        <div className="text-left space-y-2">
                            <div>
                                <p className="text-xs text-gray-500 dark:text-gray-400">Name</p>
                                <p className="font-mono text-lg text-gray-800 dark:text-gray-100">{user.name}</p>
                            </div>
                            <div>
                                <p className="text-xs text-gray-500 dark:text-gray-400">Unique ID</p>
                                <p className="font-mono text-lg text-gray-800 dark:text-gray-100">{user.uniqueId}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
             <div className="flex justify-end space-x-3 p-4 bg-gray-50 dark:bg-gray-900/50 rounded-b-lg no-print">
                <button type="button" onClick={onClose} className={secondaryButtonStyle}>Close</button>
                <button type="button" onClick={() => window.print()} className={buttonStyle}>
                    <PrinterIcon className="w-5 h-5"/>
                    Print ID Card
                </button>
            </div>
        </Modal>
    );
};

const CategoryModal: React.FC<{ category?: Category; onSave: (category: Category) => void; onCancel: () => void }> = ({ category, onSave, onCancel }) => {
    const [name, setName] = useState(category?.name || '');
    
    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        onSave({ id: category?.id || `cat-${Date.now()}`, name });
    };

    return (
        <Modal title={category ? 'Edit Category' : 'Create Category'} onClose={onCancel} size="md">
             <form onSubmit={handleSubmit} className="space-y-4 p-6">
                <div>
                    <label className="block text-sm font-medium mb-1">Category Name</label>
                    <input type="text" value={name} onChange={e => setName(e.target.value)} className={inputStyle} required />
                </div>
                <div className="flex justify-end space-x-3 pt-4">
                    <button type="button" onClick={onCancel} className={secondaryButtonStyle}>Cancel</button>
                    <button type="submit" className={buttonStyle}>Save Category</button>
                </div>
            </form>
        </Modal>
    );
};


const ClassModal: React.FC<{ classData?: Class; onSave: (classData: Class, userIds: string[]) => void; onCancel: () => void }> = ({ classData, onSave, onCancel }) => {
    const context = useContext(AppContext);
    const [name, setName] = useState(classData?.name || '');
    const [selectedUsers, setSelectedUsers] = useState<string[]>([]);
    
    useEffect(() => {
        if(classData && context){
            const userIds = context.classAssignments.filter(ca => ca.classId === classData.id).map(ca => ca.userId);
            setSelectedUsers(userIds);
        }
    }, [classData, context]);

    if (!context) return null;
    const { users } = context;

    const handleUserToggle = (userId: string) => {
        setSelectedUsers(prev => prev.includes(userId) ? prev.filter(id => id !== userId) : [...prev, userId]);
    };

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        onSave({ id: classData?.id || `class-${Date.now()}`, name }, selectedUsers);
    };

    return (
        <Modal title={classData ? 'Edit Class' : 'Create Class'} onClose={onCancel}>
            <form onSubmit={handleSubmit} className="space-y-4 p-6">
                <div>
                    <label className="block text-sm font-medium mb-1">Class Name</label>
                    <input type="text" value={name} onChange={e => setName(e.target.value)} className={inputStyle} required />
                </div>
                <div>
                    <label className="block text-sm font-medium mb-1">Assign Students</label>
                    <div className="max-h-60 overflow-y-auto border dark:border-gray-600 rounded-md p-2 space-y-2">
                        {users.filter(u => u.role === Role.USER).map(user => (
                            <label key={user.id} className="flex items-center space-x-3 p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-700">
                                <input type="checkbox" checked={selectedUsers.includes(user.id)} onChange={() => handleUserToggle(user.id)} className="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500" />
                                <span>{user.name}</span>
                            </label>
                        ))}
                    </div>
                </div>
                 <div className="flex justify-end space-x-3 pt-4">
                    <button type="button" onClick={onCancel} className={secondaryButtonStyle}>Cancel</button>
                    <button type="submit" className={buttonStyle}>Save Class</button>
                </div>
            </form>
        </Modal>
    );
};

const QuizModal: React.FC<{ quiz?: Quiz, onSave: (quiz: Quiz) => void; onCancel: () => void }> = ({ quiz, onSave, onCancel }) => {
    const context = useContext(AppContext);
    const [title, setTitle] = useState(quiz?.title || '');
    const [description, setDescription] = useState(quiz?.description || '');
    const [timeLimit, setTimeLimit] = useState(quiz?.timeLimit || 10);
    const [category, setCategory] = useState(quiz?.category || 'Uncategorized');
    const [questions, setQuestions] = useState<Question[]>(quiz?.questions || [{ id: `q-${Date.now()}`, text: '', options: ['', '', '', ''], correctAnswerIndex: 0 }]);
    const [randomizeQuestions, setRandomizeQuestions] = useState(quiz?.randomizeQuestions || false);

    const handleQuestionChange = (index: number, field: keyof Question, value: any) => {
        const newQuestions = [...questions];
        (newQuestions[index] as any)[field] = value;
        setQuestions(newQuestions);
    };
    
    const handleOptionChange = (qIndex: number, oIndex: number, value: string) => {
        const newQuestions = [...questions];
        newQuestions[qIndex].options[oIndex] = value;
        setQuestions(newQuestions);
    };

    const addQuestion = () => {
        setQuestions([...questions, { id: `q-${Date.now()}`, text: '', options: ['', '', '', ''], correctAnswerIndex: 0 }]);
    };
    
    const removeQuestion = (index: number) => {
        if(questions.length <= 1) return;
        setQuestions(questions.filter((_, i) => i !== index));
    };

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        onSave({
            id: quiz?.id || `quiz-${Date.now()}`,
            title,
            description,
            timeLimit,
            category,
            questions,
            randomizeQuestions
        });
    };

    return (
        <Modal title={quiz ? 'Edit Quiz' : 'Create Quiz'} onClose={onCancel} size="3xl">
            <form onSubmit={handleSubmit} className="space-y-6 p-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                        <label className="block text-sm font-medium mb-1">Title</label>
                        <input type="text" value={title} onChange={e => setTitle(e.target.value)} className={inputStyle} required />
                    </div>
                    <div>
                        <label className="block text-sm font-medium mb-1">Time Limit (minutes)</label>
                        <input type="number" value={timeLimit} onChange={e => setTimeLimit(Number(e.target.value))} className={inputStyle} min="1" required />
                    </div>
                </div>
                <div>
                    <label className="block text-sm font-medium mb-1">Description</label>
                    <textarea value={description} onChange={e => setDescription(e.target.value)} className={inputStyle} rows={2}></textarea>
                </div>
                 <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-center">
                    <div>
                        <label className="block text-sm font-medium mb-1">Category</label>
                        <select value={category} onChange={e => setCategory(e.target.value)} className={inputStyle}>
                            {context?.categories.map(c => <option key={c.id} value={c.name}>{c.name}</option>)}
                        </select>
                    </div>
                    <div className="pt-6">
                        <label className="flex items-center space-x-3 cursor-pointer">
                            <input
                                type="checkbox"
                                checked={randomizeQuestions}
                                onChange={e => setRandomizeQuestions(e.target.checked)}
                                className="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500"
                            />
                            <span className="text-sm font-medium text-gray-700 dark:text-gray-300">Randomize Question Order</span>
                        </label>
                    </div>
                </div>
                <hr className="dark:border-gray-600"/>
                <div>
                    <h4 className="text-lg font-semibold mb-3">Questions</h4>
                    <div className="space-y-6">
                        {questions.map((q, qIndex) => (
                            <div key={q.id} className="p-4 border dark:border-gray-700 rounded-lg bg-gray-50 dark:bg-gray-800/50">
                                <div className="flex justify-between items-center mb-3">
                                    <label className="font-semibold">Question {qIndex + 1}</label>
                                    <button type="button" onClick={() => removeQuestion(qIndex)} className={deleteIconStyle} disabled={questions.length <= 1}>
                                        <TrashIcon className="w-5 h-5"/>
                                    </button>
                                </div>
                                <textarea 
                                    value={q.text} 
                                    onChange={e => handleQuestionChange(qIndex, 'text', e.target.value)} 
                                    className={inputStyle} 
                                    placeholder="Question text"
                                    rows={2} required />
                                <div className="mt-3 space-y-2">
                                    {q.options.map((opt, oIndex) => (
                                        <div key={oIndex} className="flex items-center space-x-3">
                                            <input 
                                                type="radio" 
                                                name={`correct-answer-${qIndex}`} 
                                                checked={q.correctAnswerIndex === oIndex} 
                                                onChange={() => handleQuestionChange(qIndex, 'correctAnswerIndex', oIndex)}
                                                className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300"
                                            />
                                            <input 
                                                type="text" 
                                                value={opt} 
                                                onChange={e => handleOptionChange(qIndex, oIndex, e.target.value)} 
                                                className={inputStyle} 
                                                placeholder={`Option ${oIndex + 1}`} required />
                                        </div>
                                    ))}
                                </div>
                            </div>
                        ))}
                    </div>
                    <button type="button" onClick={addQuestion} className={`${secondaryButtonStyle} mt-4`}>
                        <PlusCircleIcon className="w-5 h-5"/>
                        Add Question
                    </button>
                </div>

                <div className="flex justify-end space-x-3 pt-4">
                    <button type="button" onClick={onCancel} className={secondaryButtonStyle}>Cancel</button>
                    <button type="submit" className={buttonStyle}>Save Quiz</button>
                </div>
            </form>
        </Modal>
    );
};

const AssignQuizModal: React.FC<{ quiz: Quiz, onSave: (quizId: string, userIds: string[], classIds: string[]) => void, onCancel: () => void }> = ({ quiz, onSave, onCancel }) => {
    const context = useContext(AppContext);
    const [selectedUsers, setSelectedUsers] = useState<string[]>([]);
    const [selectedClasses, setSelectedClasses] = useState<string[]>([]);

    useEffect(() => {
        if(context) {
            const userIds = context.assignments.filter(a => a.quizId === quiz.id).map(a => a.userId);
            const classIds = context.classQuizAssignments.filter(cqa => cqa.quizId === quiz.id).map(cqa => cqa.classId);
            setSelectedUsers(userIds);
            setSelectedClasses(classIds);
        }
    }, [quiz, context]);
    
    if(!context) return null;
    const { users, classes } = context;

    const handleUserToggle = (userId: string) => setSelectedUsers(p => p.includes(userId) ? p.filter(id => id !== userId) : [...p, userId]);
    const handleClassToggle = (classId: string) => setSelectedClasses(p => p.includes(classId) ? p.filter(id => id !== classId) : [...p, classId]);
    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        onSave(quiz.id, selectedUsers, selectedClasses);
    }
    
    return (
        <Modal title={`Assign Quiz: ${quiz.title}`} onClose={onCancel}>
            <form onSubmit={handleSubmit} className="space-y-6 p-6">
                 <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                        <h4 className="font-semibold mb-2">Assign to Users</h4>
                         <div className="max-h-60 overflow-y-auto border dark:border-gray-600 rounded-md p-2 space-y-2">
                            {users.filter(u => u.role === Role.USER).map(user => (
                                <label key={user.id} className="flex items-center space-x-3 p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-700">
                                    <input type="checkbox" checked={selectedUsers.includes(user.id)} onChange={() => handleUserToggle(user.id)} className="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500" />
                                    <span>{user.name}</span>
                                </label>
                            ))}
                        </div>
                    </div>
                    <div>
                        <h4 className="font-semibold mb-2">Assign to Classes</h4>
                         <div className="max-h-60 overflow-y-auto border dark:border-gray-600 rounded-md p-2 space-y-2">
                            {classes.map(c => (
                                <label key={c.id} className="flex items-center space-x-3 p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-700">
                                    <input type="checkbox" checked={selectedClasses.includes(c.id)} onChange={() => handleClassToggle(c.id)} className="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500" />
                                    <span>{c.name}</span>
                                </label>
                            ))}
                        </div>
                    </div>
                 </div>
                 <div className="flex justify-end space-x-3 pt-4">
                    <button type="button" onClick={onCancel} className={secondaryButtonStyle}>Cancel</button>
                    <button type="submit" className={buttonStyle}>Save Assignments</button>
                </div>
            </form>
        </Modal>
    );
};

const ClassReportModal: React.FC<{ classData: Class; onClose: () => void }> = ({ classData, onClose }) => {
    const context = useContext(AppContext);
    if (!context) return null;
    const { users, classAssignments, results, quizzes } = context;

    const studentIds = classAssignments.filter(ca => ca.classId === classData.id).map(ca => ca.userId);
    const students = users.filter(u => studentIds.includes(u.id));

    const getStudentResults = (userId: string) => {
        return results.filter(r => r.userId === userId).sort((a,b) => new Date(b.completedAt).getTime() - new Date(a.completedAt).getTime());
    };

    return (
        <Modal title={`Class Report`} onClose={onClose} size="3xl">
            <div className="printable-content p-6">
                 <h1 className="text-2xl font-bold mb-1">Class Report</h1>
                 <p className="text-lg font-semibold text-gray-700 dark:text-gray-200">{classData.name}</p>
                 <p className="text-sm text-gray-500 dark:text-gray-400 mb-6">Generated on: {new Date().toLocaleDateString()}</p>

                 <div className="space-y-8">
                    {students.map(student => {
                        const studentResults = getStudentResults(student.id);
                        let totalScore = 0;
                        let totalPossible = 0;
                        studentResults.forEach(r => {
                           totalScore += r.score;
                           totalPossible += r.totalQuestions;
                        });
                        const averagePercentage = totalPossible > 0 ? Math.round((totalScore / totalPossible) * 100) : 0;

                        return (
                           <div key={student.id} className="mb-8 p-4 border dark:border-gray-700 rounded-lg">
                               <div className="flex justify-between items-center mb-4 pb-3 border-b dark:border-gray-700">
                                   <h3 className="text-xl font-semibold text-gray-800 dark:text-white">{student.name}</h3>
                                   {studentResults.length > 0 && (
                                       <div className="text-right">
                                           <p className="font-semibold text-sm text-gray-600 dark:text-gray-300">Overall Average</p>
                                           <p className={`text-2xl font-bold ${averagePercentage >= 70 ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400'}`}>
                                               {averagePercentage}%
                                           </p>
                                       </div>
                                   )}
                               </div>
                               {studentResults.length > 0 ? (
                                   <table className="min-w-full text-sm">
                                       <thead className="text-left text-gray-500 dark:text-gray-400">
                                           <tr>
                                               <th className="px-4 py-2 font-medium">Quiz</th>
                                               <th className="px-4 py-2 font-medium">Score</th>
                                               <th className="px-4 py-2 font-medium">Date</th>
                                           </tr>
                                       </thead>
                                       <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                                           {studentResults.map(result => {
                                               const quiz = quizzes.find(q => q.id === result.quizId);
                                               const percentage = Math.round((result.score / result.totalQuestions) * 100);
                                               return (
                                                   <tr key={result.id}>
                                                       <td className="px-4 py-2 font-medium text-gray-800 dark:text-gray-200">{quiz?.title || 'Unknown Quiz'}</td>
                                                       <td className="px-4 py-2">
                                                           <span className={`font-semibold ${percentage >= 70 ? 'text-green-600 dark:text-green-500' : 'text-red-600 dark:text-red-500'}`}>{percentage}%</span>
                                                           <span className="text-gray-500 dark:text-gray-400 ml-2">({result.score}/{result.totalQuestions})</span>
                                                       </td>
                                                       <td className="px-4 py-2 text-gray-500 dark:text-gray-400">{new Date(result.completedAt).toLocaleDateString()}</td>
                                                   </tr>
                                               );
                                           })}
                                       </tbody>
                                   </table>
                               ) : (
                                   <p className="text-gray-500 dark:text-gray-400 text-center py-4">No quiz results found for this student.</p>
                               )}
                           </div>
                        );
                    })}
                 </div>
            </div>

            <div className="flex justify-end space-x-3 p-4 bg-gray-50 dark:bg-gray-900/50 rounded-b-lg no-print">
                <button type="button" onClick={onClose} className={secondaryButtonStyle}>Close</button>
                <button type="button" onClick={() => window.print()} className={buttonStyle}>
                    <PrinterIcon className="w-5 h-5"/>
                    Print Report
                </button>
            </div>
        </Modal>
    );
};


// #endregion

// #region Management Tabs

const ManageQuizzes: React.FC<{
    setModalState: React.Dispatch<any>;
    onDeleteQuiz: (quiz: Quiz) => void;
    onDeleteSelectedQuizzes: (quizIds: string[]) => void;
}> = ({ setModalState, onDeleteQuiz, onDeleteSelectedQuizzes }) => {
    const context = useContext(AppContext);
    const [selectedQuizzes, setSelectedQuizzes] = useState<string[]>([]);
    const [searchTerm, setSearchTerm] = useState('');

    if (!context) return null;
    const { quizzes, saveQuiz } = context;

    const filteredQuizzes = quizzes.filter(quiz =>
        quiz.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
        quiz.category.toLowerCase().includes(searchTerm.toLowerCase())
    );

    const handleSelectAll = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.checked) {
            setSelectedQuizzes(filteredQuizzes.map(q => q.id));
        } else {
            setSelectedQuizzes([]);
        }
    };

    const handleSelectQuiz = (quizId: string) => {
        setSelectedQuizzes(prev =>
            prev.includes(quizId) ? prev.filter(id => id !== quizId) : [...prev, quizId]
        );
    };

    const handleDeleteSelected = () => {
        onDeleteSelectedQuizzes(selectedQuizzes);
        setSelectedQuizzes([]);
    };

    const handleDuplicateQuiz = (quiz: Quiz) => {
        const newQuiz = {
            ...quiz,
            id: `quiz-${Date.now()}`,
            title: `${quiz.title} (Copy)`
        };
        saveQuiz(newQuiz);
    };

    return (
        <div>
            <div className="flex justify-between items-center mb-4">
                <input
                    type="text"
                    placeholder="Search by title or category..."
                    value={searchTerm}
                    onChange={e => setSearchTerm(e.target.value)}
                    className={`${inputStyle} max-w-sm`}
                />
                {selectedQuizzes.length > 0 ? (
                    <button onClick={handleDeleteSelected} className={deleteButtonStyle}>
                        <TrashIcon className="w-5 h-5"/>
                        Delete Selected ({selectedQuizzes.length})
                    </button>
                ) : null}
            </div>
            <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                    <thead className="bg-gray-50 dark:bg-gray-700">
                        <tr>
                            <th scope="col" className="p-4">
                                <input type="checkbox" className="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500"
                                    checked={selectedQuizzes.length > 0 && selectedQuizzes.length === filteredQuizzes.length}
                                    onChange={handleSelectAll}
                                    aria-label="Select all quizzes"
                                />
                            </th>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Title</th>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Category</th>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Questions</th>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Time Limit</th>
                            <th scope="col" className="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
                        {filteredQuizzes.map(quiz => (
                            <tr key={quiz.id}>
                                <td className="p-4">
                                    <input type="checkbox" className="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500"
                                        checked={selectedQuizzes.includes(quiz.id)}
                                        onChange={() => handleSelectQuiz(quiz.id)}
                                        aria-label={`Select quiz ${quiz.title}`}
                                    />
                                </td>
                                <td className="px-6 py-4 whitespace-nowrap">
                                    <div className="text-sm font-medium text-gray-900 dark:text-white">{quiz.title}</div>
                                    <div className="text-sm text-gray-500 dark:text-gray-400">{quiz.description}</div>
                                </td>
                                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">{quiz.category}</td>
                                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">{quiz.questions.length}</td>
                                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">{quiz.timeLimit} min</td>
                                <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <div className="flex justify-end items-center space-x-2">
                                        <button onClick={() => setModalState({ type: 'assign_quiz', quiz })} className={actionIconStyle} title="Assign Quiz">
                                            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 11a1 1 0 00-1-1h-2v2a1 1 0 002 0v-1z" /></svg>
                                        </button>
                                        <button onClick={() => handleDuplicateQuiz(quiz)} className={actionIconStyle} title="Duplicate Quiz">
                                            <DocumentDuplicateIcon className="w-5 h-5"/>
                                        </button>
                                        <button onClick={() => setModalState({ type: 'edit_quiz', quiz })} className={actionIconStyle} title="Edit Quiz">
                                            <PencilIcon className="w-5 h-5"/>
                                        </button>
                                        <button onClick={() => onDeleteQuiz(quiz)} className={deleteIconStyle} title="Delete Quiz">
                                            <TrashIcon className="w-5 h-5"/>
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

const ManageUsers: React.FC<{
    setModalState: React.Dispatch<any>;
    onDeleteUser: (user: User) => void;
    onDeleteSelectedUsers: (userIds: string[]) => void;
}> = ({ setModalState, onDeleteUser, onDeleteSelectedUsers }) => {
    const context = useContext(AppContext);
    const [searchTerm, setSearchTerm] = useState('');
    const [selectedUsers, setSelectedUsers] = useState<string[]>([]);

    if (!context) return null;
    const { currentUser, users, classes, classAssignments } = context;

    const getUserClasses = (userId: string) => {
        const assignments = classAssignments.filter(ca => ca.userId === userId);
        return assignments.map(a => classes.find(c => c.id === a.classId)?.name).filter(Boolean).join(', ');
    };

    const filteredUsers = users.filter(user => {
        const lowerCaseSearchTerm = searchTerm.toLowerCase();
        const userClasses = getUserClasses(user.id).toLowerCase();

        return (
            user.name.toLowerCase().includes(lowerCaseSearchTerm) ||
            user.uniqueId.toLowerCase().includes(lowerCaseSearchTerm) ||
            userClasses.includes(lowerCaseSearchTerm)
        );
    });

    const handleSelectAll = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.checked) {
            setSelectedUsers(filteredUsers.map(u => u.id));
        } else {
            setSelectedUsers([]);
        }
    };

    const handleSelectUser = (userId: string) => {
        setSelectedUsers(prev =>
            prev.includes(userId) ? prev.filter(id => id !== userId) : [...prev, userId]
        );
    };

    const handleDeleteSelected = () => {
        onDeleteSelectedUsers(selectedUsers);
        setSelectedUsers([]);
    };

    return (
        <div>
             <div className="flex justify-between items-center mb-4">
                <input
                    type="text"
                    placeholder="Search by name, ID, or class..."
                    value={searchTerm}
                    onChange={e => setSearchTerm(e.target.value)}
                    className={`${inputStyle} max-w-sm`}
                />
                {selectedUsers.length > 0 ? (
                    <button onClick={handleDeleteSelected} className={deleteButtonStyle}>
                        <TrashIcon className="w-5 h-5"/>
                        Delete Selected ({selectedUsers.length})
                    </button>
                ) : null}
            </div>
            <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                    <thead className="bg-gray-50 dark:bg-gray-700">
                        <tr>
                            <th scope="col" className="p-4">
                                <input type="checkbox" className="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500"
                                    checked={selectedUsers.length > 0 && selectedUsers.length === filteredUsers.length}
                                    onChange={handleSelectAll}
                                    aria-label="Select all users"
                                />
                            </th>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Name</th>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Unique ID</th>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Role</th>
                            <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Classes</th>
                            <th scope="col" className="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
                        {filteredUsers.map(user => (
                            <tr key={user.id}>
                                <td className="p-4">
                                    <input type="checkbox" className="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500"
                                        checked={selectedUsers.includes(user.id)}
                                        onChange={() => handleSelectUser(user.id)}
                                        aria-label={`Select user ${user.name}`}
                                    />
                                </td>
                                <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-white">{user.name}</td>
                                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">{user.uniqueId}</td>
                                <td className="px-6 py-4 whitespace-nowrap">
                                    <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${user.role === Role.ADMIN ? 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-300' : 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300'}`}>
                                        {user.role}
                                    </span>
                                </td>
                                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">{getUserClasses(user.id)}</td>
                                <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <div className="flex justify-end items-center space-x-2">
                                        <button onClick={() => setModalState({ type: 'view_id_card', user })} className={actionIconStyle} title="View ID Card">
                                            <IdCardIcon className="w-5 h-5"/>
                                        </button>
                                        <button onClick={() => setModalState({ type: 'edit_user', user })} className={actionIconStyle} title="Edit User">
                                            <PencilIcon className="w-5 h-5"/>
                                        </button>
                                        <button onClick={() => onDeleteUser(user)} className={deleteIconStyle} title="Delete User" disabled={currentUser?.id === user.id}>
                                            <TrashIcon className="w-5 h-5"/>
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

const ManageClasses: React.FC<{
    setModalState: React.Dispatch<any>;
    onDeleteClass: (classData: Class) => void;
}> = ({ setModalState, onDeleteClass }) => {
    const context = useContext(AppContext);
    if (!context) return null;
    const { classes, classAssignments } = context;

    const getStudentCount = (classId: string) => {
        return classAssignments.filter(ca => ca.classId === classId).length;
    };

    return (
        <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                <thead className="bg-gray-50 dark:bg-gray-700">
                    <tr>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Class Name</th>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Students</th>
                        <th scope="col" className="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Actions</th>
                    </tr>
                </thead>
                <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
                    {classes.map(classData => (
                        <tr key={classData.id}>
                            <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-white">{classData.name}</td>
                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">{getStudentCount(classData.id)}</td>
                            <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                <div className="flex justify-end items-center space-x-2">
                                    <button onClick={() => setModalState({ type: 'view_class_report', classData })} className={actionIconStyle} title="View Class Report">
                                        <ChartBarIcon className="w-5 h-5"/>
                                    </button>
                                    <button onClick={() => setModalState({ type: 'edit_class', classData })} className={actionIconStyle} title="Edit Class">
                                        <PencilIcon className="w-5 h-5"/>
                                    </button>
                                    <button onClick={() => onDeleteClass(classData)} className={deleteIconStyle} title="Delete Class">
                                        <TrashIcon className="w-5 h-5"/>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
};

const ManageCategories: React.FC<{
    setModalState: React.Dispatch<any>;
    onDeleteCategory: (category: Category) => void;
}> = ({ setModalState, onDeleteCategory }) => {
    const context = useContext(AppContext);
    if (!context) return null;
    const { categories } = context;

    return (
        <div className="overflow-x-auto max-w-2xl">
            <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                <thead className="bg-gray-50 dark:bg-gray-700">
                    <tr>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Category Name</th>
                        <th scope="col" className="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">Actions</th>
                    </tr>
                </thead>
                <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
                    {categories.map(category => (
                        <tr key={category.id}>
                            <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-white">{category.name}</td>
                            <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                <div className="flex justify-end items-center space-x-2">
                                    <button onClick={() => setModalState({ type: 'edit_category', category })} className={actionIconStyle} title="Edit Category" disabled={category.name === 'Uncategorized'}>
                                        <PencilIcon className="w-5 h-5"/>
                                    </button>
                                    <button onClick={() => onDeleteCategory(category)} className={deleteIconStyle} title="Delete Category" disabled={category.name === 'Uncategorized'}>
                                        <TrashIcon className="w-5 h-5"/>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
};

// #endregion

export const AdminDashboard: React.FC = () => {
    const [activeTab, setActiveTab] = useState('quizzes');
    const [modalState, setModalState] = useState<any>(null);
    const [confirmation, setConfirmation] = useState<{
        isOpen: boolean;
        title: string;
        message: string;
        onConfirm: () => void;
    } | null>(null);

    const context = useContext(AppContext);
    
    if (!context) return null;
    const { saveQuiz, deleteQuiz, assignQuiz, assignQuizToClasses, saveUser, deleteUser, saveClass, deleteClass, saveCategory, deleteCategory } = context;

    const handleCloseModal = () => setModalState(null);
    const handleCloseConfirmation = () => setConfirmation(null);

    const handleConfirm = () => {
        if (confirmation?.onConfirm) {
            confirmation.onConfirm();
        }
        handleCloseConfirmation();
    };

    const handleDeleteQuiz = (quiz: Quiz) => {
        setConfirmation({
            isOpen: true,
            title: `Delete Quiz`,
            message: `Are you sure you want to delete "${quiz.title}"? This will also remove all assignments and results. This action cannot be undone.`,
            onConfirm: () => deleteQuiz(quiz.id),
        });
    };

    const handleDeleteSelectedQuizzes = (quizIds: string[]) => {
        setConfirmation({
            isOpen: true,
            title: `Delete ${quizIds.length} Quizzes`,
            message: `Are you sure you want to delete ${quizIds.length} selected quizzes? This action cannot be undone.`,
            onConfirm: () => quizIds.forEach(id => deleteQuiz(id)),
        });
    };

    const handleDeleteUser = (user: User) => {
        setConfirmation({
            isOpen: true,
            title: 'Delete User',
            message: `Are you sure you want to delete the user "${user.name}"? This action cannot be undone.`,
            onConfirm: () => deleteUser(user.id),
        });
    };

    const handleDeleteSelectedUsers = (userIds: string[]) => {
        setConfirmation({
            isOpen: true,
            title: `Delete ${userIds.length} Users`,
            message: `Are you sure you want to delete ${userIds.length} selected users? This action cannot be undone.`,
            onConfirm: () => userIds.forEach(id => deleteUser(id)),
        });
    };

    const handleDeleteClass = (classData: Class) => {
        setConfirmation({
            isOpen: true,
            title: 'Delete Class',
            message: `Are you sure you want to delete the class "${classData.name}"? All student and quiz assignments for this class will be removed.`,
            onConfirm: () => deleteClass(classData.id),
        });
    };
    
    const handleDeleteCategory = (category: Category) => {
        setConfirmation({
            isOpen: true,
            title: 'Delete Category',
            message: `Are you sure you want to delete the category "${category.name}"? Quizzes in this category will be moved to "Uncategorized".`,
            onConfirm: () => deleteCategory(category.id),
        });
    };

    const handleSaveQuiz = (quiz: Quiz) => {
        saveQuiz(quiz);
        handleCloseModal();
    };

    const handleSaveUser = (user: User) => {
        saveUser(user);
        handleCloseModal();
    };
    
    const handleSaveClass = (classData: Class, userIds: string[]) => {
        saveClass(classData, userIds);
        handleCloseModal();
    };
    
    const handleAssignQuiz = (quizId: string, userIds: string[], classIds: string[]) => {
        assignQuiz(quizId, userIds);
        assignQuizToClasses(quizId, classIds);
        handleCloseModal();
    };

    const handleSaveCategory = (category: Category) => {
        saveCategory(category);
        handleCloseModal();
    };

    const renderModal = () => {
        if (!modalState) return null;

        switch (modalState.type) {
            case 'create_quiz':
                return <QuizModal onSave={handleSaveQuiz} onCancel={handleCloseModal} />;
            case 'edit_quiz':
                return <QuizModal quiz={modalState.quiz} onSave={handleSaveQuiz} onCancel={handleCloseModal} />;
            case 'assign_quiz':
                return <AssignQuizModal quiz={modalState.quiz} onSave={handleAssignQuiz} onCancel={handleCloseModal} />;
            case 'create_user':
                return <UserModal onSave={handleSaveUser} onCancel={handleCloseModal} />;
            case 'edit_user':
                return <UserModal user={modalState.user} onSave={handleSaveUser} onCancel={handleCloseModal} />;
            case 'view_id_card':
                return <IdCardModal user={modalState.user} onClose={handleCloseModal} />;
            case 'create_class':
                return <ClassModal onSave={handleSaveClass} onCancel={handleCloseModal} />;
            case 'edit_class':
                return <ClassModal classData={modalState.classData} onSave={handleSaveClass} onCancel={handleCloseModal} />;
            case 'view_class_report':
                return <ClassReportModal classData={modalState.classData} onClose={handleCloseModal} />;
            case 'create_category':
                return <CategoryModal onSave={handleSaveCategory} onCancel={handleCloseModal} />;
            case 'edit_category':
                return <CategoryModal category={modalState.category} onSave={handleSaveCategory} onCancel={handleCloseModal} />;
            default:
                return null;
        }
    };

    const tabContent: { [key: string]: React.ReactNode } = {
        'quizzes': <ManageQuizzes setModalState={setModalState} onDeleteQuiz={handleDeleteQuiz} onDeleteSelectedQuizzes={handleDeleteSelectedQuizzes} />,
        'users': <ManageUsers setModalState={setModalState} onDeleteUser={handleDeleteUser} onDeleteSelectedUsers={handleDeleteSelectedUsers} />,
        'classes': <ManageClasses setModalState={setModalState} onDeleteClass={handleDeleteClass} />,
        'categories': <ManageCategories setModalState={setModalState} onDeleteCategory={handleDeleteCategory} />,
    };

    const tabConfig = [
        { id: 'quizzes', label: 'Manage Quizzes', icon: <DocumentTextIcon className="w-5 h-5 mr-2"/> },
        { id: 'users', label: 'Manage Users', icon: <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 mr-2" viewBox="0 0 20 20" fill="currentColor"><path d="M9 6a3 3 0 11-6 0 3 3 0 016 0zM17 6a3 3 0 11-6 0 3 3 0 016 0zM12.93 17c.046-.327.07-.66.07-1a6.97 6.97 0 00-1.5-4.33A5 5 0 0119 16v1h-6.07zM6 11a5 5 0 015 5v1H1v-1a5 5 0 015-5z" /></svg> },
        { id: 'classes', label: 'Manage Classes', icon: <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 mr-2" viewBox="0 0 20 20" fill="currentColor"><path d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z" /></svg> },
        { id: 'categories', label: 'Manage Categories', icon: <TagIcon className="w-5 h-5 mr-2"/> }
    ];

    const getHeaderButton = () => {
         switch (activeTab) {
            case 'quizzes': return <button onClick={() => setModalState({ type: 'create_quiz' })} className={buttonStyle}><PlusCircleIcon className="w-5 h-5"/> New Quiz</button>;
            case 'users': return <button onClick={() => setModalState({ type: 'create_user' })} className={buttonStyle}><PlusCircleIcon className="w-5 h-5"/> New User</button>;
            case 'classes': return <button onClick={() => setModalState({ type: 'create_class' })} className={buttonStyle}><PlusCircleIcon className="w-5 h-5"/> New Class</button>;
            case 'categories': return <button onClick={() => setModalState({ type: 'create_category' })} className={buttonStyle}><PlusCircleIcon className="w-5 h-5"/> New Category</button>;
            default: return null;
         }
    };

    return (
        <div className="container mx-auto p-4 sm:p-6 lg:p-8">
            {renderModal()}
            {confirmation?.isOpen && (
                <ConfirmationModal
                    title={confirmation.title}
                    message={confirmation.message}
                    onConfirm={handleConfirm}
                    onCancel={handleCloseConfirmation}
                />
            )}
            <div className="flex flex-col md:flex-row justify-between items-center mb-6">
                <div>
                    <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Admin Dashboard</h1>
                    <p className="text-lg text-gray-600 dark:text-gray-400 mt-1">Manage quizzes, users, and classes.</p>
                </div>
                {getHeaderButton()}
            </div>

            <div className="mb-6">
                <div className="border-b border-gray-200 dark:border-gray-700">
                    <nav className="-mb-px flex space-x-4 overflow-x-auto" aria-label="Tabs">
                         {tabConfig.map(tab => (
                            <button key={tab.id} onClick={() => setActiveTab(tab.id)} className={`${tabStyle} ${activeTab === tab.id ? activeTabStyle : inactiveTabStyle}`}>
                                {tab.icon}
                                {tab.label}
                            </button>
                        ))}
                    </nav>
                </div>
            </div>

            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
                {tabContent[activeTab]}
            </div>
        </div>
    );
};
